#!/usr/bin/env python3
"""第 1 步：切片 —— 整个 RAG 里最影响效果的一环。

    python tutorial/1_chunk.py

它把一堆源文件变成一堆 chunk（代码片段）。后面所有环节都建立在这一步之上：
切片切歪了，换什么模型都救不回来。

三个关键决策，每一个都有代价：

  1. 切片单位 = AST 节点（class / function / method），不按行数切
     按行数切会在函数正中间下刀，切出来的两半都答不出完整问题。

  2. 类和方法分开
     类单独一个 chunk，只含「类签名 + docstring + 类级字段」；
     每个方法各自一个 chunk。否则一个 300 行的类会变成一个巨型 chunk，
     问其中任何一个方法都要把整个类塞给模型。

  3. 不生成 module 级 chunk
     模块开头那一段全是 import。如果它单独成一个 chunk，检索时会命中
     一堆毫无信息量的 import 段。imports 作为「元数据」挂到同文件
     的每个 chunk 上，而不是自己占一个位置。

跑完请重点看打印出来的三样东西：
  被排除了哪些文件 / 抽出来的 chunk 长什么样 / 调用关系抽到了什么
"""

import ast
import builtins
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import CHUNKS_PATH, REPO, banner  # noqa: E402

# ---------------------------------------------------------------- 排除规则

# 三层排除，从粗到细。顺序很重要：先便宜的后贵的。
EXCLUDE_DIRS = {"generated", "__pycache__", ".git", "node_modules", ".venv"}
EXCLUDE_PATTERNS = ("*.min.js", "*.pb.go", "*.generated.*")

# 第三层是最容易漏、污染最重的一层。
# 很多生成文件叫 api_client.py / models.py，从名字完全看不出来是生成的，
# 只有看内容才知道。toy_repo/generated/api_client.py 就是这种情况。
CONTENT_MARKERS = ("DO NOT EDIT", "Code generated by", "@generated", "AUTOGENERATED")
SCAN_HEAD_LINES = 30

MAX_LINES = 150  # 超过这个长度的函数要再切一层，玩具库里没有，见文件末尾说明


def should_exclude(path, rel):
    """返回排除原因，不排除则返回 None。三层按顺序过，命中就停。"""
    # set 去重
    parts = set(rel.split("/"))
    hit = parts & EXCLUDE_DIRS
    # 被命中需要忽略
    if hit:
        # set 集合转换成 list
        return f"目录名 {sorted(hit)}"

    if any(path.match(p) for p in EXCLUDE_PATTERNS):
        return f"文件名模式 {path.name}"

    try:
        head = "\n".join(path.read_text(errors="ignore").splitlines()[:SCAN_HEAD_LINES])
    except OSError:
        return "读不了"
    for marker in CONTENT_MARKERS:
        if marker in head:
            return f"内容标记 {marker!r}"

    return None


def iter_files(root):
    """扫出所有要索引的 .py 文件，同时返回被排除的清单。"""
    kept, dropped = [], []
    # rglob("*.py") 等价于 glob("**/*.py")
    for path in sorted(root.rglob("*.py")):
        # 去前缀取相对路径  as_posix() 转字符串
        rel = path.relative_to(root).as_posix()
        reason = should_exclude(path, rel)
        (dropped if reason else kept).append((path, rel, reason))
    return kept, dropped


# ---------------------------------------------------------------- AST 切片

DEF_NODES = (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)


def walk_with_chain(node, chain=()):
    """递归遍历 AST，同时带上父节点链 —— 面包屑全靠它。

    chain 是「外层名字」的元组，比如 ('UserService',)。
    ast.walk 不带这个信息，所以必须自己递归。
    """
    for child in ast.iter_child_nodes(node):
        if isinstance(child, DEF_NODES):
            yield child, chain
            yield from walk_with_chain(child, chain + (child.name,))
        else:
            yield from walk_with_chain(child, chain)


def node_start(node):
    """定义起始行。有装饰器时要从装饰器算起，否则装饰器会被切在外面。"""
    if node.decorator_list:
        return min(d.lineno for d in node.decorator_list)
    return node.lineno


def func_signature(node):
    """拼出函数签名。喂给 embedding 的不是整个函数体，签名信息密度最高。"""
    args = ast.unparse(node.args)
    ret = f" -> {ast.unparse(node.returns)}" if node.returns else ""
    prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
    return f"{prefix} {node.name}({args}){ret}"


def class_signature(node):
    """拼出类签名，带上基类。"""
    bases = ", ".join(ast.unparse(b) for b in node.bases)
    return f"class {node.name}({bases})" if bases else f"class {node.name}"


def class_header_end(node):
    """类 chunk 到哪一行结束：只取 docstring 和类级字段，方法另算。

    这样 UserService 这类大类不会变成一个巨型 chunk。
    """
    stmts = head_stmts(node)
    return stmts[-1].end_lineno if stmts else node.lineno


BUILTIN_NAMES = set(dir(builtins))


def extract_calls(nodes):
    """抽出这些节点里调用了哪些东西。传列表是因为类的头部有多个语句。

    这是「这个函数被谁调用」类问题的唯一可靠来源 ——
    调用关系是确定性事实，靠向量猜必错。

    两个细节，都是踩过的坑：
      - 内置符号要过滤掉。不过滤的话 ValueError / print / len 会混进来，
        结果「谁调用了 ValueError」这种噪声淹掉真正的关系。
      - 静态抽取只能拿到「名字」，拿不到「定义在哪」：
        self.login() 只能拿到 'login'，它属于哪个类静态分析不一定定得下来。
        真实工程要靠作用域表或 tree-sitter 的 scope 分析补。
    """
    names = set()
    for root in nodes:
        for sub in ast.walk(root):
            if not isinstance(sub, ast.Call):
                continue
            fn = sub.func
            if isinstance(fn, ast.Name):
                names.add(fn.id)
            elif isinstance(fn, ast.Attribute):
                names.add(fn.attr)
    return sorted(n for n in names if n not in BUILTIN_NAMES)


def head_stmts(node):
    """类的头部语句：docstring + 类级字段，不含方法。

    用来保证「类 chunk 的 calls」和「类 chunk 的 code」是同一个范围 ——
    否则类 chunk 只有 5 行代码，却带着整个类 30 行的调用关系，
    后面查「谁调用了 X」就会莫名其妙命中类的头部。
    """
    out = []
    for stmt in node.body:
        # print(f"stmt :{stmt},{stmt.value}")
        is_docstring = (
            isinstance(stmt, ast.Expr)
            and isinstance(stmt.value, ast.Constant)
            and isinstance(stmt.value.value, str)
        )
        if is_docstring or isinstance(stmt, (ast.AnnAssign, ast.Assign)):
            out.append(stmt)
            continue
        break
    return out


def extract_imports(tree):
    """文件级 import 列表。挂到该文件每个 chunk 的 imports 字段上。"""
    out = []
    # 遍历整个 ast 树
    for node in ast.walk(tree):
        # print('node',ast.dump(node, indent=2))
        if isinstance(node, ast.Import):
            out += [a.name for a in node.names]
        elif isinstance(node, ast.ImportFrom):
            out.append(node.module or ".")
    return sorted(set(out))


def make_chunk(node, source_lines, rel, chain, imports, project):
    """把一个 AST 节点变成一个 chunk dict。

    schema 和正式工程完全一致，将来把教程里的逻辑搬过去不用改字段。
    """
    is_class = isinstance(node, ast.ClassDef)
    start = node_start(node)
    end = class_header_end(node) if is_class else node.end_lineno

    # 类只看头部，函数看整体 —— 保证 code 和 calls 是同一个范围
    scope = head_stmts(node) if is_class else [node]

    code = "\n".join(source_lines[start - 1 : end])
    # print(f"code",code)
    breadcrumb = " › ".join((rel, *chain, node.name))

    chunk = {
        "id": f"{project}:{rel}:{start}",
        "project": project,
        "file": rel,
        "start_line": start,
        "end_line": end,
        "language": "python",
        "kind": "class" if is_class else ("method" if chain else "function"),
        "name": node.name,
        "breadcrumb": breadcrumb,
        "signature": class_signature(node) if is_class else func_signature(node),
        "docstring": ast.get_docstring(node) or "",
        "code": code,
        "imports": imports,
        "calls": extract_calls(scope),
    }
    return chunk


def embedding_text(chunk):
    """真正喂给 embedding 模型的文本。

    注意不是 chunk["code"]。只喂原始代码的话，import 段、样板代码
    会主导向量，语义全被冲淡。
    """
    parts = [
        f"# {chunk['breadcrumb']}",
        chunk["signature"],
        chunk["docstring"],
        chunk["code"],
    ]
    return "\n".join(p for p in parts if p)


def chunk_file(path, rel, project):
    """切一个文件。语法错误的文件直接跳过，别让一个坏文件中断整批。"""
    text = path.read_text(errors="ignore")
    try:
        tree = ast.parse(text)
    except SyntaxError as exc:
        print(f"  [跳过] {rel}: 语法错误 {exc}")
        return []

    lines = text.splitlines()
    imports = extract_imports(tree)
    return [
        make_chunk(node, lines, rel, chain, imports, project)
        for node, chain in walk_with_chain(tree)
    ]


# ---------------------------------------------------------------- 主流程


def main():
    banner("第 1 步：切片")

    kept, dropped = iter_files(REPO)
    print(f"扫到 {len(kept) + len(dropped)} 个 .py 文件\n")
    print("被排除的（三层规则）：")
    for _path, rel, reason in dropped:
        print(f"  - {rel:32s} {reason}")
    if not dropped:
        print("  (无)")

    chunks = []
    for path, rel, _ in kept:
        chunks += chunk_file(path, rel, project="toy_repo")

    CHUNKS_PATH.write_text(
        "".join(json.dumps(c, ensure_ascii=False) + "\n" for c in chunks),
        encoding="utf-8",
    )

    banner("切片结果")
    print(f"共 {len(chunks)} 个 chunk -> {CHUNKS_PATH}\n")
    print("按 kind 分布：")
    for kind in ("class", "method", "function"):
        n = sum(1 for c in chunks if c["kind"] == kind)
        print(f"  {kind:9s} {n}")

    lines = [c["end_line"] - c["start_line"] + 1 for c in chunks]
    print(f"\n行数：最小 {min(lines)} / 中位 {sorted(lines)[len(lines)//2]} / 最大 {max(lines)}")

    banner("抽 3 个 chunk 看看长什么样")
    for chunk in [chunks[0], chunks[4], chunks[8]]:
        print(f"\n{'─' * 64}")
        print(f"kind       : {chunk['kind']}")
        print(f"name       : {chunk['name']}")
        print(f"breadcrumb : {chunk['breadcrumb']}")
        print(f"signature  : {chunk['signature']}")
        print(f"位置       : {chunk['file']}:{chunk['start_line']}-{chunk['end_line']}")
        print(f"imports    : {chunk['imports']}")
        print(f"calls      : {chunk['calls']}")
        print("── 喂给 embedding 的文本（前 6 行）──")
        for line in embedding_text(chunk).splitlines()[:6]:
            print(f"  {line}")

    banner("调用关系（calls 表的前身）")
    for chunk in chunks:
        if "verify_password" in chunk["calls"]:
            print(f"  {chunk['breadcrumb']}  ->  verify_password")

    banner("已知限制（真实工程要处理，玩具库没遇到）")
    print("  1. 超长函数（>150 行）要按嵌套函数再切一层，本教程没实现")
    print("  2. calls 只抽到名字，没解析到定义位置（'login' 属于哪个类不知道）")
    print("  3. 只支持 Python。多语言要换 tree-sitter，见 tutorial/README.md")


if __name__ == "__main__":
    main()
